### ISSUE TITLE
[Bios 906] Bios Update tutorial is not precise enought.

### ISSUE THREAD

**Issue by lowlevl** [Cr0wTom/Mi-Notebook-Pro-Mods#9] opened 2019-06-14 02:07 UTC
The BIOS update 906 doesn't come with an EFI folder, so we need to copy the EFI folder from the 603 and proceed by typing commands, you should add that to the tutorial !
Do you want me to give you the commands ?

**Comment by Cr0wTom** [comment] 2019-06-14 08:27
As you can see in my BIOS update section I have the following:

> **UPDATE**: For the latest XMAKB5R0P0906 BIOS update, just unzip the folder and execute the H2OFFT-Wx64.exe executable, in a Windows installation.

It does not need anything else, it is a different process :)

**Comment by lowlevl** [comment] 2019-06-14 09:07
Hello @Cr0wTom, but this doesn't work for those who are using *Mac* or *Linux*, but we can proceed as follow:
1. Download the 906 **and** 603 BIOS updates.
2. Unzip the 603 update to a FAT32 formatted drive, with the EFI directory at the root of the USB drive.
3. Copy the BIOS update file **XMAKB5R0P0906.fd** from 906 and paste it at the root of the USB Stick.
4. Reboot and mash `<F12>` until you have the boot menu and boot to the USB Stick.
5. When you have a UEFI Shell, type the following command:
```
H2OFFT-Sx64.efi XMAKB5R0P0906.fd
```
6. Wait for it to reboot, flash with a progress bar, and reboot again.

**Comment by ErikSteNL** [comment] 2019-07-19 08:39
Hey, has anybody tried this? I would like to update from 502 to 906 without bricking using this method (I am using a linux distro).
Or is this safe?

**Comment by lowlevl** [comment] 2019-07-19 09:44
Yes, I did, it works great :)

**Comment by lowlevl** [comment] 2019-07-19 09:45
I think it's safe, but you take your own risks :)

**Comment by ErikSteNL** [comment] 2019-07-19 10:15
@Nurrl Thanks for the response, I'll try this method somewhere next week, I'll keep you up-to-date

**Comment by hridoy43** [comment] 2020-10-22 10:19
> Hello @Cr0wTom, but this doesn't work for those who are using _Mac_ or _Linux_, but we can proceed as follow:
> 
> 1. Download the 906 **and** 603 BIOS updates.
> 2. Unzip the 603 update to a FAT32 formatted drive, with the EFI directory at the root of the USB drive.
> 3. Copy the BIOS update file **XMAKB5R0P0906.fd** from 906 and paste it at the root of the USB Stick.
> 4. Reboot and mash `<F12>` until you have the boot menu and boot to the USB Stick.
> 5. When you have a UEFI Shell, type the following command:
> 
> ```
> H2OFFT-Sx64.efi XMAKB5R0P0906.fd
> ```
> 
> 1. Wait for it to reboot, flash with a progress bar, and reboot again.

Tried this But getting an error that "Permission denied by user". Anyone faced this? and How can I fix this?

**Comment by HorrZzz** [comment] 2021-03-23 04:43
> > Hello @Cr0wTom, but this doesn't work for those who are using _Mac_ or _Linux_, but we can proceed as follow:
> > 
> > 1. Download the 906 **and** 603 BIOS updates.
> > 2. Unzip the 603 update to a FAT32 formatted drive, with the EFI directory at the root of the USB drive.
> > 3. Copy the BIOS update file **XMAKB5R0P0906.fd** from 906 and paste it at the root of the USB Stick.
> > 4. Reboot and mash `<F12>` until you have the boot menu and boot to the USB Stick.
> > 5. When you have a UEFI Shell, type the following command:
> > 
> > ```
> > H2OFFT-Sx64.efi XMAKB5R0P0906.fd
> > ```
> > 
> > 
> > 
> > 1. Wait for it to reboot, flash with a progress bar, and reboot again.
> 
> Tried this But getting an error that "Permission denied by user". Anyone faced this? and How can I fix this?

I have the same problem……

**Comment by floydkretschmar** [comment] 2021-10-12 20:37
I am not sure how relevant this still is to @HorrZzz or anyone else in this thread, but after I spend half a day looking for solutions, and I actually found one on another website, I am going to share it here, in case any future google archeologist is searching for this problem. All credit to the absolute legend BRichards from the comment thread on this techtablets blog: https://techtablets.com/2017/12/xiaomi-mi-notebook-pro-nvme-ssd-bios-pcie-x2-fix/

"I had the same error. Just remove your fingerprint and pincode ID first from your windows settings.
After you typed in unlock me and the system reboots, log into windows with your password, then reboot again (F12 to USB) and then type ‘flash’ after the prompt.
BTW no significant change in the fan speed up for me."

**Comment by Cr0wTom** [comment] 2021-11-20 14:07
Closing as the issue is fixed. If you see any discrepancy in the repo please issue a pull request and I will try to merge it asap.

**Closed as completed by Cr0wTom** 2021-11-20 14:07 UTC
