### ISSUE TITLE
XMAKB5R0P0906 bricks MX250 (2019) year version

### ISSUE THREAD

**Issue by yar-shukan** [Cr0wTom/Mi-Notebook-Pro-Mods#18] opened 2019-09-20 15:38 UTC
XMAKB5R0P0906 bricks MX250 (2019) year version

**Comment by yar-shukan** [comment] 2019-09-25 20:56
Hey @Cr0wTom , any chance you know how to fix this issue? I'd like my notebook be back, not bricked by XMAKB5R0P0906 (crying).

Just FYI the full notebook spec:
- Xiaomi Mi Notebook Pro 15.6" 2019 JYU4147CN
- Original BIOS: XMAKB5R0P0C07
- Intel Core i7 8550U
- DDR4 16 GB
- SSD 512 GB
- NVIDIA GeForce MX250 2 GB

I'd really appreciate any help from community as it's a pity that just switch from MX150 to MX250 makes this BIOS version XMAKB5R0P0906 not applicable and it bricks PC.

**Comment by Cr0wTom** [comment] 2019-09-25 21:00
Man why did you used a BIOS that is not intended for your device! You have to triple check for these things every time!

Is it a hardbrick? Can you do anything at all? I do not thing that it is easily fixable if you cannot go to bios and boot from a stick though!

**Comment by yar-shukan** [comment] 2019-09-25 21:30
Honestly I didn't expect that just MX250 change would brick the PC because I have another one with MX150 and it worked fine with that one. As I know MX250 is technically MX150 with increased clock speed (according to [this](https://www.notebookcheck.net/GeForce-MX150-vs-GeForce-MX250-vs-GeForce-MX230_8000_9561_9571.247598.0.html)).

Damn, you need to be very explicit on such things with 100 (**!!!!!!!!!!!!!!**) in readme not to have fools like me bricking their new shiny MIs :(

Is there any plans to support MX250 version as well?

**Comment by Cr0wTom** [comment] 2019-09-25 21:38
Sorry man but I explicitly say "Modification collection for the i5/i7 Mi Notebook Pro (with the MX150 GPU)."

Because on paper you see that the only change is the GPU it doesn't mean that everything else is the same! There are many components on a complete system as a laptop that the average consumer doesn't care to know about!

And no, sorry but the problem is not the 100 !!!!! but the thing that you don't have a technical background and patch whatever you find in the wild! Please be careful next time, and try to get it fixed with your warranty if you have one!

No, I do not plan to support it because I do not have one and I do not plan on buying one. 

I am really sorry for your device I will see if there is something else that you can do! 

Update: https://en.miui.com/thread-1735432-1-1.html

**Comment by yar-shukan** [comment] 2019-09-25 21:57
I totally agree and I believe me I saw this line, but really was dumb to hurry with the action. Not trying to blame anyone, just I guess I'm not the last one shooting into the foot...
 
I do have tech background, but not that much hardware one... Anyway, just curios: any way to inject check that BIOS is not compatible with the target device to terminate the update or somehow WARN poor fool end user like me?

**Comment by aleqssss** [comment] 2019-09-30 12:11
I have the same issue. Downgrade from 0C07...
I think we need a BIOS backup of this version, then we could try to flash the BIOS chip with a ch341 ^^

**Comment by Cr0wTom** [comment] 2021-11-20 13:57
Closing the issue as it is unrelated to this repo.

**Closed as completed by Cr0wTom** 2021-11-20 13:57 UTC
